### ISSUE TITLE
The "AvaloniaStatsTask" task failed unexpectedly

### ISSUE THREAD

**Issue by derekantrican** [AvaloniaUI/Avalonia.HtmlRenderer#25]
I've cloned the repo & I'm trying to build HtmlRenderer.Demo.Avalonia.Desktop and I'm getting the following build error:

```
Error	MSB4018	The "AvaloniaStatsTask" task failed unexpectedly.
System.IO.IOException: The semaphore timeout period has expired.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Pipes.NamedPipeClientStream.Connect(Int32 timeout)
   at Avalonia.Telemetry.AvaloniaStatsTask.ConnectToPipe()
   at Avalonia.Telemetry.AvaloniaStatsTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	Avalonia.HtmlRenderer	C:\Users\deantric\.nuget\packages\avalonia.buildservices\0.0.12\buildTransitive\Avalonia.BuildServices.targets	9	
```

Any tips?

**Comment by derekantrican** [comment]
Nevermind - after cleaning & rebuilding individual projects up the dependency chain, I got it to work. Weird.
